spring:
  application:
    name: SpringSecurity

  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: minhhieu
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081


application:
    jwt:
        secret-key: 39c658a258a42e6ea83c38b59ed9f78076f2d3cf75ec8eb3d80e3aa433370e4a
        access-token:
            expiration: 3600 # seconds
        refresh-token:
            expiration: 3600 # 1 hour
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /api-docs
