
name: Development CI-CD

on:
  push:
    branches: [ "develop" ]
  pull_request_target:
    branches: [ "develop" ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Run Maven Build Command
      run: mvn clean install -DskipTests -Pdevelopment
    - name: Run Maven Test
      run: mvn test -Pdevelopment
    - name: Unit Test Results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Development-Unit-Test-Results
        path: ${{ github.workspace }}/target/surefire-reports/*.xml
        reporter: java-junit

