
name: Development CI-CD

on:
  push:
    branches: [ "develop" ]
  pull_request_target:
    branches: [ "develop" ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Run Maven Build Command
      run: mvn clean install -DskipTests -Pdevelopment
    - name: Run Maven Test
      run: mvn test -Pdevelopment
    - name: Unit Test Results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Development-Unit-Test-Results
        path: target/surefire-reports/*.xml
        reporter: java-junit
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: |
          duongminhhieu008/rookie-phase1-development
          ghcr.io/${{ github.repository }}
    - name: Build and push Docker images
      id: push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

